### ISSUE TITLE
ゲーム開始のカウントダウン中にバックキーを押すとアプリが落ちる

### ISSUE THREAD

**Issue by quotto** [quotto/throwtrash-android#25]

**Comment by quotto** [comment]
> Process: net.wackwack.pic_card_memory, PID: 3895
>                                                                                                     java.lang.NullPointerException: null cannot be cast to non-null type androidx.constraintlayout.widget.ConstraintLayout
>                                                                                                     	at net.wackwack.pic_card_memory.game.view.GameMainFragment.showCountDown$lambda$11$lambda$10$lambda$9$lambda$8$lambda$7$lambda$6$lambda$5$lambda$4(GameMainFragment.kt:320)
>                                                                                                     	at net.wackwack.pic_card_memory.game.view.GameMainFragment.$r8$lambda$x5W9r8ao0Oi_yNPegbz2RC_O16A(Unknown Source:0)
>                                                                                                     	at net.wackwack.pic_card_memory.game.view.GameMainFragment$$ExternalSyntheticLambda2.run(Unknown Source:2)
>                                                                                                     	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1120)
>                                                                                                     	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
>                                                                                                     	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
>                                                                                                     	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
>                                                                                                     	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
>                                                                                                     	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
>                                                                                                     	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
>                                                                                                     	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
>                                                                                                     	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
>                                                                                                     	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
>                                                                                                     	at android.view.Choreographer.doFrame(Choreographer.java:827)
>                                                                                                     	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
>                                                                                                     	at android.os.Handler.handleCallback(Handler.java:942)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:201)
>                                                                                                     	at android.os.Looper.loop(Looper.java:288)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:7872)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
